name: to_do_list_app
description: "Your best to-do list"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_it: ^7.7.0
  talker_flutter: ^4.1.3
  auto_route: ^8.1.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_slidable: ^3.1.0
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/
    - assets/fonts/
